### ISSUE TITLE
Submit a Pull Request when dependencies are updated

### ISSUE THREAD

**Issue by pathawks** [parkr/auto-reply#10]
It would be awesome if @jekyllbot could periodically check to make sure that all dependencies are up to date. If not, it could submit a Pull Request with the updated version, which would then trigger CI with the updated versions.

RubyGems.org has a nice API to poll for the latest version of a Gem: `https://rubygems.org/api/v1/versions/rubocop/latest.json`

The bot would just need to be triggered to periodically check for this.

**Comment by parkr** [comment]
#22 and #23 now do this.

Example: https://github.com/jekyll/jekyll/issues/5772
