### ISSUE TITLE
Add has-pull-request label

### ISSUE THREAD

**Issue by pathawks** [parkr/auto-reply#11]
If I add a PR with the line `Fixes #1234`, then issue 1234 should be labeled `has-pull-request`

Bonus points for removing the label if my PR is closed without merging.

**Comment by parkr** [comment]
Love this idea.

**Comment by thiagoarrais** [comment]
I'm willing to try this. I figured my first step would be to try to run my own bot instance. But I hit into some issues trying to get an `auto-reply` server running as per README. Here's what I've got so far: 

https://gist.github.com/thiagoarrais/d1114d9d69342bf180afe8f1b33924b7

By the way, I am a total Go newbie. Should I keep on going this way? Or should I approach this some other way?

**Comment by parkr** [comment]
@thiagoarrais I just updated the README. Can you try using the new code I pushed? Copy the new contents of the README to your file and run 

```console
$ go get -u github.com/parkr/auto-reply
$ go build
```

It should then create a binary without issues. Thanks for noticing that the docs were out of date!

**Comment by thiagoarrais** [comment]
Thanks, @parkr. I've managed to receive an event now. Next step: have affinity assign an issue to me.
