### ISSUE TITLE
Do not assign issue creator

### ISSUE THREAD

**Issue by pathawks** [parkr/auto-reply#21]
I feel funny when @jekyllbot assigns me to an issue that I created.

I would rather either:

 1. It _never_ assign my issues to me, and try to find somebody else for purposes of accountability _or_
 2. It _always_ assign my issues to me. If I am a collaborator and I create an issue, I am ultimately the one who is responsible for it, and I probably know who I should ask for a review or whatnot.

**Comment by parkr** [comment]
Does #16 work?

**Comment by pathawks** [comment]
Yessir, thank you :+1:
