### ISSUE TITLE
Escape titles before adding to History

### ISSUE THREAD

**Issue by pathawks** [parkr/auto-reply#25]
If the title of a PR is `Feed entries must contain <author>` and **auto-reply** adds that to `History.markdown` as is, then when parsed the line [will appear as](https://github.com/jekyll/jekyll-feed/blob/v0.9.0/History.markdown#minor-enhancements) `Feed entries must contain ` because Markdown is trying to parse the tag as HTML.

It would probably be a good idea anyway to just escape any special characters before writing to `History.markdown`

**Comment by parkr** [comment]
👍

**Comment by parkr** [comment]
Relevant line: https://github.com/parkr/auto-reply/blob/bc2314e0b858666550b4ed667343329ecd84b1b9/chlog/merge_and_label.go#L292
