### ISSUE TITLE
Dependency issue tickets and `has-pull-request` label

### ISSUE THREAD

**Issue by ashmaroli** [parkr/auto-reply#26]
Hi,
Making a note here that when a `Fixes #<issue-id>` was added to a PR to fix a `Dependency Constraint` issue raised by JekyllBot, the `has-pull-request` label was not added to the concerned issue ticket.

This could be because of one-or-more of the following:
  - The author did not include that statement when creating the PR.
  - It was subsequently added by **another person** with write-access.
  - There were two separate directives of `Fixes #<issue-id-1>\nFixes #<issue-id-2>` for multiple issues instead of including them in the same directive. `Fixes #<issue-id-1>, #<issue-id-2>`
  - The directive was dispatched from an older issue-id (`PR #6093`) to a newer id (`Issue #6101`)

Either ways, I expect that JekyllBot adds the label when instructed:
  - by **anyone with write-access**, 
  - **anywhere in the PR**,
  - **any no.of times** (may require validation though)

Ref: jekyll/jekyll#6101 and jekyll/jekyll#6093

**Comment by parkr** [comment]
https://github.com/parkr/auto-reply/blob/741bc72ea8fa868726d615bddc05c3f949dd57a6/labeler/has_pull_request.go#L41-L59 is the code for this. Perhaps the regexp is wrong.

**Comment by parkr** [comment]
> `Already bumped in #6093`

That's not a valid link.

What this webhook does is it accepts new pull request webhook payloads and if it says it fixes/closes an issue, it gives that issue the label. It doesn't work the other way. So 6101 isn't a valid example. 

I added a test for 6093 and it passed. dc60b5c

**Comment by ashmaroli** [comment]
Ok Thanks,
6101 wasn't an example. But a reference..
Anyways, will come back to this if I can provide a reproducible scenario

**Comment by parkr** [comment]
Thanks! 😄 Yeah, any unique tests you want to try out should show whether it extracts the right info.
