### ISSUE TITLE
Clean `pending-feedback` issues

### ISSUE THREAD

**Issue by pathawks** [parkr/auto-reply#27]
**The problem:** Some people will open an issue and disappear from the surface of the planet. After a month @jekyllbot will complain, and after two months @jekyllbot will close. Meanwhile, the issue will rot in an inactionable state.

**The solution:** If an issue tagged `pending-feedback` has no response, @jekyllbot should *close* the issue with a message explaining why and advising the OP to reopen the issue if/when more information can be provided. Perhaps this could happen faster than issues are marked `stale`, for instance: two weeks after being marked `pending-feedback`

**Comment by parkr** [comment]
❤️

**Comment by parkr** [comment]
Done in 3810605.
