### ISSUE TITLE
Add `update-docs` label 

### ISSUE THREAD

**Issue by DirtyF** [parkr/auto-reply#28]
Not every PR needs documentation, but it would be nice to at least have such a label for PR lacking documentation update.

Similar to https://probot.github.io/apps/update-docs/

**Comment by parkr** [comment]
We should just install that probot plugin! I much prefer letting someone else write and maintain it :) if it’s not a good fit then we could consider an extension here, or try to ask the maintainers of that plugin to modify it for our needs :)
