### ISSUE TITLE
Create an Issue when it's time for a new release

### ISSUE THREAD

**Issue by pathawks** [parkr/auto-reply#29]
It would be nice if @jekyllbot could create a new issue when it looks like it is time to release a new version. The issue could be closed and ignored, but it would serve as a nice reminder for maintainers.

It could simply count the number of commits since the last release and open an issue when that number crosses a threshold.

OR it could use `History.md` to detect the number of PRs (rather than commits) since the last release and open an issue when _that_ number crosses a threshold.

POSSIBLY it could exclude **dev** only changes from counting toward that threshold. Things like Rubocop changes don't change functionality, and don't merit a new release.

BONUS POINTS if it could create a PR that automatically calculated the appropriate version number (based on previous version number and if there are any major/minor changes included in this new version) and updated `History.md` and `gemspec` accordingly. Then a maintainer would need only merge the PR and tag a release. Then Travis could cut a :gem:gem, and @jekyllbot would fill in the release notes on the  GitHub Release.

**Comment by DirtyF** [comment]
This has been fixed.

**Comment by parkr** [comment]
One thing I noticed a couple days ago was that the Stale issue closer will close these new release issues! I’d love to make sure it doesn’t do that.

**Comment by DirtyF** [comment]
Could #50 help with that?

**Comment by parkr** [comment]
Yes :)
