### ISSUE TITLE
Add descriptions and emojis to labels

### ISSUE THREAD

**Issue by DirtyF** [parkr/auto-reply#38]
https://github.com/blog/2505-label-improvements-emoji-descriptions-and-more

Right now if a label is modified, jekyllbot creates a new one, leading to duplicates:

https://github.com/jekyll/jekyll/labels

**Comment by parkr** [comment]
Go allows Unicode so you should be able to update the list to include emoji :smile:

When the code is looking for similarities, we could be smarter and strip to ascii and lowercase label names. Then we could replace the non-emojified label with the emojified label!
