### ISSUE TITLE
LGTM deprecated in favour of 'Pull Request Reviews'

### ISSUE THREAD

**Issue by ghost** [parkr/auto-reply#8]
[Pull request reviews](https://help.github.com/articles/about-pull-request-reviews/) should, eventually, deprecate the LGTM module, specifically:

> **Approve**: Submit feedback and approve merging the changes proposed in the pull request.
> 
> Repository administrators can use [protected branches](https://help.github.com/articles/about-protected-branches) to require that all pull requests receive at least one _approved_ review before they can be merged into the branch.

Discuss. :smile:

**Comment by parkr** [comment]
I want to be able to require a certain number of review approvals, so I'm probably going to revive the LGTM module to use Pull Request Review webhooks once they're released. 👍

**Comment by benbalter** [comment]
LGTM.

**Comment by parkr** [comment]
Requesting reviews as of: f63f1ac2ff144ba5a7a172314bedd350875d6c02
