### ISSUE TITLE
Try to automatically clean up Rubocop violations

### ISSUE THREAD

**Issue by pathawks** [parkr/auto-reply#9]
I'm not sure exactly how it might work, but there are times when a Pull Request introduces violations that Rubocop is capable of fixing with a simple `rubocop -a`

It would be nice if @jekyllbot could clone the PR branch, run `rubocop -a`, commit the changes if all violations have been corrected, and push the commit to the same PR branch (assuming push access).

It would be awesome if @jekyllbot could subscribe to Travis notifications and be automatically notified when a Rubocop violation occurs. Short of that, perhaps one could explicitly ask @jekyllbot to try to clean up violations.

Is this a crazy pipe dream?

**Comment by parkr** [comment]
jekyllbot has a Ruby environment so theoretically this is a possibility. It runs Ruby `1.9.3p484`, so the current Rubocop version won't work with it. This may be a crazy pipe dream since this project is a Go project :/

**Comment by parkr** [comment]
I'd rather ask people to do this. Easy contributions. 😄
